services:
  mysql:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root1234
      - MYSQL_DATABASE=obligatorio_db
      - MYSQL_USER=obligatorio_usr
      - MYSQL_PASSWORD=db_pwd_1223334444
    ports:
      - "3306:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysql", "-h", "localhost", "-u", "obligatorio_usr", "-pdb_pwd_1223334444", "-e", "USE obligatorio_db"]
      interval: 5s
      timeout: 50s
      retries: 10
  frontend:
    build: ./frontend
    ports:
      - "80:80"
  backend:
    build: ./backend
    environment:
      - USER_NAME=root
      - DB_PASSWORD=db_pwd_1223334444
      - DB_USER_NAME=obligatorio_usr
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/obligatorio_db
      - JWT_SECRET_PATH=/run/secrets/jwt-secret
      - EMAIL=correoAutomaticoLA@outlook.com
      - EMAIL_PASSWORD_PATH=/run/secrets/email-pwd
    ports:
      - "8080:8080"
    volumes:
      - type: bind
        source: ./jwt-secret
        target: /run/secrets/jwt-secret
        read_only: true
      - type: bind
        source: ./email-pwd
        target: /run/secrets/email-pwd
        read_only: true
    secrets:
      - jwt-secret
      - email-pwd
    depends_on:
      mysql:
        condition: service_healthy

secrets:
  jwt-secret:
    file: ./jwt-secret
  email-pwd:
    file: ./email-pwd