version: '3'
services:
  mysql:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root1234
      - MYSQL_DATABASE=obligatorio_db
      - MYSQL_USER=obligatorio_usr
      - MYSQL_PASSWORD=db_pwd_1223334444
    ports:
      - "3306:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "bash", "-c", "mysql --user=$$USER_NAME --password=$$MYSQL_PASSWORD --execute 'SHOW DATABASES;'"]
      interval: 5s
      timeout: 50s
      retries: 10
  backend:
    build: ./backend
    environment:
      - USER_NAME=root
      - DB_PASSWORD=db_pwd
      - DB_USER_NAME=obligatorio_db
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/obligatorio_db
      - EMAIL=obligatorio17@outlook.com
      - EMAIL_PASSWORD=obligatorio_17
      - REDIS_HOST=redis
      - JWT_SECRET_PATH=/run/secrets/jwt-secret
      - EMAIL=correoAutomaticoLA@outlook.com
      - EMAIL_PASSWORD_PATH=/run/secrets/email-pwd
    ports:
      - "8080:8080"
    volumes:
      - /run/secrets:/run/secrets:ro
    secrets:
      - jwt-secret
      - email-pwd
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_started