spring:
  application:
    name: PencaUCU
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${DB_USER_NAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql

security:
  jwt:
    expiration-time-in-days: 10